### ISSUE TITLE
command.get is not a function

### ISSUE THREAD

**Issue by matthewhutchings** [aschmelyun/cleaver#65]
command.get('php cleaver build', (error, stdout, stderr) => {
                            ^

TypeError: command.get is not a function

when running npm run watch and trying to save a file

**Comment by aaftre** [comment]
```
Building Site
=============
+ hello-world.json rendered to /

» 1 page built in 58.41ms


/app/webpack.mix.js:30
                    command.get('php cleaver build', (error, stdout, stderr) => {
                            ^

TypeError: command.get is not a function
    at Object.fn (/app/webpack.mix.js:30:29)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (/app/node_modules/chokidar/index.js:541:32)
    at FSWatcher._emit (/app/node_modules/chokidar/index.js:632:8)
    at listener (/app/node_modules/chokidar/lib/nodefs-handler.js:370:20)

Node.js v17.9.0
```
